- name: Loadbalancer
  hosts: loadbalancer
  become: yes

  vars:
    upstream_name: "webservers"
    webservers:
      - webserver1
      - webserver2


  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Configure Loadbalancer
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: restart nginx

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

